name: Dungeons
version: '${version}'
main: ru.shirk.dungeons.Dungeons
api-version: '1.16'
depend: [WorldEdit, WorldGuard]
authors: [shirkqqe]
description: Dungeons
website: https://github.com/shirkqqe

commands:
  dungeons:
    description: ""
  generatedungeons:
    description: ""
permissions:
  dungeons.admin:
    default: op
